### PR TITLE
bsc#1080332, split large strings into smaller combination

### PR DESCRIPTION
**Pull request by nick-wang**
Split the large help strings source into smaller strings combination to ease the work of translation, version 4.0.0

### CODE REVIEW

**Comment by stanislav-brabec** [comment]
Now strings look much better. The change will need adjustment of all translations in yast-translations, and additionally some Weblate updates to keep existing suggestions. I just locked the [Weblate project](https://l10n.opensuse.org/projects/yast-iplb/master/).

**Comment by lslezak** [comment]
@nick-wang: I still have some questions:

Do we actually need such long and detailed help texts?

I mean it's OK to have a good help text but is this text already available somewhere else? Does our documentation cover this topic? Or is there some online documentation? In that case a simple link might be enough...

**Comment by stanislav-brabec** [comment]
I am not sure what is the standard way to translate helps, but all-in-one-msgid was surely a wrong way. Imagine that English text changes one character, and the whole string becomes fuzzy.

However these strings were translated. For several languages not only once, but even twice. Once by community, second time by contracted translators. I am now working on splitting them by articles, so reviewers will be able to compare both translations.

If you will migrate translations in future, please let me know to save expenses. It contains hundreds of pages of text.

**Comment by stanislav-brabec** [comment]
After the split, the gettext indicates that the exactly same article appears on two places. E. g. the one starting with "</p><p><b><big>check timeout</big> =</b> <i>n</i>". Is it intended?

Now we have up to 4 different translations for such articles: instance 1 from the community, instance 2 from the community, instance 1 from contracted translators, instance 2 from contracted translators.

**Comment by nick-wang** [comment]
@lslezak sorry for the late reply, since i just back from a long vacation.
Most contents are included in man page, besides some limitation and recommendation in yast module.
So yes, I think i can simplify it in the next release.

**Comment by nick-wang** [comment]
@stanislav-brabec Thanks for the translation. 
This time only split into pieces without any modification. I think i can simplify the text in future to ease the work.

**Comment by stanislav-brabec** [comment]
To save existing translation work. I just spent several days in splitting of existing translations. Translations as well as suggestion were successfully processed.

The old source repeated some identical columns in two strings. It forced translators to translate the same text twice. As SUSE Linux Enterprise had its own translation in past, up to 4 translations exists for some strings. It was a big waste of translators work.

Now these 3 translations exist as suggestions, at least until translators will review it.

In case of future change, please keep in mind, that the total amount of translation work in these strings reached ~50000 words. If you will drop or change these helps, all this work will be lost.

**Pull request merged**
